# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'scorpio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Realm','3.7.5'
  pod 'RealmSwift','3.7.5'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  
  target 'scorpioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'scorpioUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
